fix(tests): More tests fixes.
fix(tests): Fix hangup by avoiding not defined error.

ReferenceError: APP is not defined.

fix(tests): Fix reference to APP in debug logs retrieval

Avoids `ReferenceError: APP is not defined` the failure may happen after hangup where APP is not defined.

Minor test fixes (#16577)

* test: Increase password dialog timeout.
* test: Try to fix hangup().

feat(tests): Drop more aria selectors.

fix(tests): Send logs to browser to keep correct order.

feat(tests): Uses memory logs on failure and stops logging during conference.

feat(tests): Avoids using aria selector for breakout rooms.

It is reported to be slow at times.

fix(tests) Increase backToP2PDelay to 3 secs.
Setting it to 1 sec was causing p2p connections to be created when it was not needed.

feat(tests): Fail early and gather debug logs for iframe tests.