fix(api) regression in background toggle command
Commit 1aca8ab98 added a leading name parameter to all dialogs for
logging. `toggle-virtual-background` lacks this parameter, leading to:

```
Error: Minified React error #130; visit https://react.dev/errors/130?args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. [object Object]: https://meet.example.com/libs/app.bundle.min.js?v=9268 +2
```

followed by an XMPP disconnect.